package cn.tedu.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2019-01-14T15:02:14.449+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://ws.tedu.cn/", name = "DataTypeWS")
@XmlSeeAlso({ObjectFactory.class})
public interface DataTypeWS {

    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getAllStudens", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.GetAllStudens")
    @WebMethod
    @ResponseWrapper(localName = "getAllStudensResponse", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.GetAllStudensResponse")
    public cn.tedu.ws.GetAllStudensResponse.Return getAllStudens();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsBySalary", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.GetStudentsBySalary")
    @WebMethod
    @ResponseWrapper(localName = "getStudentsBySalaryResponse", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.GetStudentsBySalaryResponse")
    public java.util.List<cn.tedu.ws.Student> getStudentsBySalary(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.AddStudent")
    @WebMethod
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        cn.tedu.ws.Student arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.GetStudentById")
    @WebMethod
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://ws.tedu.cn/", className = "cn.tedu.ws.GetStudentByIdResponse")
    public cn.tedu.ws.Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
